A whole buncha changes. Mainly the menu.
tacosConference/tacosConference.github.io pull request #85
Opened 2023-02-18 16:48 UTC by ansost

## SERVE LOCALLY BEFORE APPROVING.

This is a lot of changes, this is not good practice but sue me. 

## The menu bar now includes all subsections

FYI I move the scholarship section below the sponsors since I felt that they kind of belong to eachother (?). Feel free to reverse that tho. 
One could make an argument for taking scholarships out of the menu (or abbreviating it). The menu is a bit crowded right now and therefore it sinks down when you are at the top of the page.  

## Added an important dates section. 

If anybody can make a box around that section (imo not including the heading) I think that would be great. I ddin manage to make one that includes the `call for papers` and `registration` since I made those with headings and the box that I was trying to use did not permit headings in the box. 

### Added an 'm' on accommodations.

2023-02-18 17:08 UTC, BraveMoneyLute commented
wheremst
![image](https://user-images.githubusercontent.com/104856882/219878795-f417c146-4247-44a8-a023-8deb25d00b46.png)

2023-02-18 17:12 UTC, BraveMoneyLute commented on _data/twenty_23/locations.yml
> -  img: accomodation.jpg
This will just change the file akljdhalkjsdh 🤩
Please change it some lines up

2023-02-18 17:13 UTC, BraveMoneyLute commented on _includes/2023_data/about.html
> +                    <h2 class="section-heading">More Information</h2>
Keep as "About", instead dont link the first Welcome block as About, this will make it less crowded

2023-02-18 17:15 UTC, ansost commented on _data/twenty_23/locations.yml
> -  img: accomodation.jpg
I SWEAR I EDITED THE TITLE ouf. lemme just ....

2023-02-18 17:17 UTC, BraveMoneyLute commented on _includes/2023_data/header-home.html
> +                        <a class="page-scroll" href="#dates">About</a>
yeah, I wouldn't link this because its at the top of the page, we can think of letting a kind of "News Ticker" run on the top of the page, if we want to grab people's attention, but for now I think where you placed it is enough

2023-02-18 17:22 UTC, ansost commented on _includes/2023_data/about.html
> +                    <h2 class="section-heading">More Information</h2>
Agreed and done. What do you think of still callling it more info? The section doesnt feel very about-y to me.

2023-02-18 17:27 UTC, BraveMoneyLute commented on _includes/2023_data/team_members.html
> +    <section id="team" class="bg-light-gray">
So, about this, this changes some CSS styling for the Teams section, if you take a look and compare the Speakers and the Teams, you will see that speakers have a white box surrounding the centered text, but teams doesnt. Thats because the generated CSS file for Teams doesnt have the CSS lines that would format that, and I cannot tell you right now what they are, but if you would like to keep the old styling to keep the look uniform, I'd suggest you take a look again

2023-02-18 17:31 UTC, BraveMoneyLute requested changes
Let me merge after you fix some things I see you are already working on them but my internet just died and Im tethering myself mobile data

2023-02-18 17:32 UTC, ansost commented on _includes/2023_data/team_members.html
> +    <section id="team" class="bg-light-gray">
Will do:) The reasons I changed this is that the ID is used for linking with href. I'll copy the css or tho k of something else

2023-02-18 17:33 UTC, BraveMoneyLute commented on _includes/2023_data/about.html
> +                    <h2 class="section-heading">More Information</h2>
You can call it Agenda, replace Teams with FAQ and think about whether we need location or not

2023-02-18 17:34 UTC, BraveMoneyLute commented on _includes/2023_data/header-home.html
> +                        <a class="page-scroll" href="#dates">About</a>
Oh no, I think FAQ and Agenda are not sepatate sections, just call it FAQ then

2023-02-18 17:36 UTC, BraveMoneyLute commented on _includes/2023_data/about.html
> +                    <h2 class="section-heading">More Information</h2>
(this commented to the wrong section aaa ) Oh no, I think FAQ and Agenda are not sepatate sections, just call it FAQ then

2023-02-18 17:39 UTC, BraveMoneyLute commented
Also, wanna open an Issue for the Draw A Box Around The Important dates? I might be able to do that

2023-02-19 15:03 UTC, ansost commented on _includes/2023_data/team_members.html
> +    <section id="team" class="bg-light-gray">
Done. Today I learnt, that the `id` parameter is not something specific to this template or the `section` html thingy, but something that can make everything a link. Only took me 5000 hours to get to that solution but now I know.

2023-02-19 15:22 UTC, BraveMoneyLute approved these changes

2023-02-19 15:22 UTC, merged